### ISSUE TITLE
Можно ли обойтись без trov?

### ISSUE THREAD

**Issue by mad** [praimuwka/TestAnalysis#1]
Сколько требуется памяти?

Какова сложность алгоритма?

Для случаев, все в одной группе, число групп равно числу строк

**Comment by praimuwka** [comment]
> Сколько требуется памяти?
> 
> Какова сложность алгоритма?
> 
> Для случаев, все в одной группе, число групп равно числу строк

расчет в README

**Comment by egor1989** [comment]
@mad
